# Use the official Python image as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Install required Python packages
RUN pip install paho-mqtt cryptography pymysql

