= SAE 3.01 2023-2024
:toc:
:toc-title: Sommaire
//:toc: preamble
:toclevels: 5
:sectnums:
:sectnumlevels: 5

:Entreprise: Groupe 1
:Equipe:  

== Présentation de l'équipe et rôles respectifs

Lors de cette SAE nous allons colllaborer en équipe de 4 afin de réaliser ce projet. Les membres de notre équipe sont respectivement :

* https://github.com/Iamkylian[Kylian GACHET] - SCRUM MASTER
* https://github.com/YannRouquie[Yann ROUQUIE] - PRODUCT OWNER
* https://github.com/MatheoKatbie[Mathéo KATBIE] - DEVELOPPEUR
* https://github.com/Lyll01[Lylian DERRAMOND] - DEVELOPPEUR

Enseignant(e) en lien avec le projet:: mailto:remi.boulle@univ-tlse2.fr[Remi Boulle]

== Présentation du projet

=== Contexte

Dans le cadre de notre SAE, nous avons pour mission de réaliser une application web permettant de visualiser les informations transmises par des capteurs situés dans les salles du Batiment B de l'IUT de Blagnac. +
Cette application permettra également de visualiser les informations relatives aux salles (température, humidité, luminosité, etc...) en temps réel ainsi que l'historique des données transmise par les capteurs, toutes ces informations seront seraccessible via un rendu graphique pour permettre une meilleur visualisation et analyse dans le cadre d'une maintenance efficace.

== Réalisations 

=== Installation de l'application

Afin de pouvoir utiliser l'application de maniére efficace et fonctionnels, il est nécessaire de suivre les étapes suivantes :

- 1. Installer https://www.docker.com/products/docker-desktop/[Docker Desktop] et le lancer
- 2. Cloner le répository

    $ git clone [lien du repository]

- 3. Si ce n'est pas le cas, se placer sur la branche main

    $ git checkout main

- 3. Récupérer le projet localement

    $ git pull

- 4. Ouvrir un terminal dans le dossier /Docker du projet

    $ cd ./Docker/ 

- 5. Exécuter la commande :

    $ docker-compose up -d

- 6. Se rendre sur l'addresse  http://localhost:8000/ pour visualiser l'interface

=== Localisation des fichiers

Le dépot Github est séparé en plusieurs dossiers, chacun ayant un rôle bien précis :

- https://github.com/Iamkylian/SAE-ALT-BUT3B01/tree/main/BDD[/BDD] : contient les fichiers de intéragissant avec la base de données SQL
- https://github.com/Iamkylian/SAE-ALT-BUT3B01/tree/main/Documentation[/Docker] : contient les fichiers nécessaires à la configuration et au fonctionnement de l'application
- https://github.com/Iamkylian/SAE-ALT-BUT3B01/tree/main/Documentation[/Documentation] : contient les documents relatifs à l'application
- https://github.com/Iamkylian/SAE-ALT-BUT3B01/tree/main/Python[/Python] : contient les fichiers sources de l'application

== Gestion de projet & Qualité

- Version courante : https://github.com/IUT-Blagnac/sae3-01-template/releases/tag/v0.1.2[v0.1.2]
- image:https://img.shields.io/badge/V1-red?style=flat&label=Documentation%20Technique&link=https%3A%2F%2Fgithub.com%2FIamkylian%2FSAE-ALT-BUT3B01%2Ftree%2Fmain%2FDocumentation%2FDocumentation-Technique.adoc[Static Badge]
- image:https://img.shields.io/badge/Documentation%Utilisateur-Version%201.0-brightgreen.svg[Version: 1.0, link="https://github.com/Iamkylian/SAE-ALT-BUT3B01/tree/main/Documentation/Documentation-Utilisateur.adoc"]
- Tests unitaires et plans de test ?
- Indicateurs de qualité du code (dette technique)
- ... tout autre élément que vous jugerez utiles pour démontrer la qualité de votre application

=== Issues

image:https://img.shields.io/github/issues/Iamkylian/SAE-ALT-BUT3B01?style=flat&label=Issues%#26[Issues #26, link="https://github.com/Iamkylian/SAE-ALT-BUT3B01/issues/26"] +
image:https://img.shields.io/github/issues/Iamkylian/SAE-ALT-BUT3B01?style=flat&label=Issues[Issues #25, link="https://github.com/Iamkylian/SAE-ALT-BUT3B01/issues/25"] +
image:https://img.shields.io/github/issues/Iamkylian/SAE-ALT-BUT3B01?style=flat&label=Issues[Issues #24, link="https://github.com/Iamkylian/SAE-ALT-BUT3B01/issues/24"] +
image:https://img.shields.io/github/issues/Iamkylian/SAE-ALT-BUT3B01?style=flat&label=Issues[Issues #23, link="https://github.com/Iamkylian/SAE-ALT-BUT3B01/issues/23"] +
image:https://img.shields.io/github/issues/Iamkylian/SAE-ALT-BUT3B01?style=flat&label=Issues[Issues #22, link="https://github.com/Iamkylian/SAE-ALT-BUT3B01/issues/22"] +
image:https://img.shields.io/github/issues/Iamkylian/SAE-ALT-BUT3B01?style=flat&label=Issues[Issues #21, link="https://github.com/Iamkylian/SAE-ALT-BUT3B01/issues/21"] +
image:https://img.shields.io/github/issues/Iamkylian/SAE-ALT-BUT3B01?style=flat&label=Issues[Issues #20, link="https://github.com/Iamkylian/SAE-ALT-BUT3B01/issues/20"] +
image:https://img.shields.io/github/issues/Iamkylian/SAE-ALT-BUT3B01?style=flat&label=Issues[Issues #19, link="https://github.com/Iamkylian/SAE-ALT-BUT3B01/issues/19"] +
image:https://img.shields.io/github/issues/Iamkylian/SAE-ALT-BUT3B01?style=flat&label=Issues[Issues #18, link="https://github.com/Iamkylian/SAE-ALT-BUT3B01/issues/18"]

== Livrables

[cols="1,2,2,5",options=header]
|===
| Date    | Nom               | Lien | Retour
|  | Documentation Utilisateur   | lien |
|  | Documentation Technique   | lien | 
|  | Backlog Produit   | lien | 
|  | Compte rendu Sprint 1 | lien | 
|  | Compte rendu Sprint 2   | lien | 
|  | Compte rendu Sprint 3   | lien | 
|===


