= Bilan du Sprint 1 - Sujet "Occupation des salles" (Occupation)
:toc:
:toc-title: Sommaire
//:toc: preamble
:toclevels: 5
:sectnums:
:sectnumlevels: 5
:date: {date}

:Entreprise: Groupe 1
:Equipe:  

[cols="4"]
|===
|Version | Date | Équipe | Projet
|1.0 | {date} | Groupe 1 : Kylian, Mathéo, Yann, Lylian | Développement d'une application
|=== 

== Description

* Sprint dates: 08/01 at 9h30, to 12/01 at 17h
* Sprint review: 12/01 at 9h30
* Sprint demo: 12/01 at 10h
* Scrum master: https://github.com/Iamkylian[Kylian GACHET]

== Objectifs

* Organiser et planfier le Github entre le Scrum Master et le Product Owner -> OK
* Définir les tâches à réaliser dans les Issues et créer les taches en lien avec le Backlog -> OK
* Créer le corps de la documentation technique et utilisateur -> OK
* Produire les bases de l'interface, la connexion à la bases de données et récupérer les flux MQTT à ingérer dans la BD -> OK

== Demo

* (release)

== FeedBack de l'equipe

Bonne organisations au sein de l'equipe, le travail est correctement répartit et les taches sont bien définies.
Le travail est bien avancé pour le sprint N°2 et les objectifs sont atteints.
Au niveau des documentation il manque encore quelques détails à ajouter mais le corps est bien présent.
Le backlog nous parait bien défini avec les details necessaires a sa compréhension.

== Sujets en progression pour le prochain sprint

* 
* 

== Documentation

== Tâches terminées

* 

== Tâches non achevées

* 

== Tâches achevées mais non planifiées

* 

== Tâches non achevées mais non planifiées

*
