= Tests de l'application Room Service

= Cahier De Recette - RoomSerivce
:toc:
:toc-title: Sommaire
:toclevels: 5
:sectnums:
:sectnumlevels: 5

:Entreprise: RoomService
:Equipe:  


[cols="5"]
|===
|Version | Date | Équipe | Projet
|3.0 | 26 Janvier 2024 | Groupe 1 : Yann, Mathéo, Kylian, Lylian | RoomService
|===  


== Introduction
=== Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet de visualisation d'occupation des salles du 1er étage du batiment informatique de l'IUT de blagnac. L'objectif principal de ce projet est de développer une interface web permettant de visualiser en temps réel les conditions des salles, mais aussi de stocker ces données de manière sécurisée. En fournissant un historique complet et des outils de statistiques, notre application vise à offrir aux utilisateurs un aperçu détaillé de l'occupation des salles.


== Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. *À vérifier*


=== Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiés dans la *documentation technique*.


=== Environnement de test :
[.text-justify]
Ordinateur sous Windows, Linux (Ubuntu).


== Cas de test :
[.text-justify]


==== Fonctionnalités utilisateurs

==== Cas de test 1 : Visualisation des informations d'une salle
[.text-justify]

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Visualisation des informations d'une salle
>|Objectif 4+| Obtenir les informations d'une salle via le capteur AM107

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer le premier étage du batiment informatique ^|La fenêtre de sélection des salles s'ouvre ^| Etre connecté à l'interface web (localhost:8000) ^|OK
^|All_G_C.2 ^|Cliquer sur une salle spécifique ^|Une fenetre d'information détaillé s'ouvre ^| Etre précédement sur la page d'acceuil  ^|OK
^|All_G_C.3 ^|Cliquer sur le bouton "Retour" ^|La fenêtre de sélection des salles s'ouvre ^|aucune ^|OK


5+|

|====


|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Visualisation de l'etat des batteries des capteurs
>|Objectif 4+| Obtenir l'etat des batteries des capteurs par salle

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur "Maintenance" ^|La fenêtre du batiment informatique s'ouvre ^| Etre connecté à l'interface web (localhost:8000) ^|OK
^|All_G_C.2 ^|Cliquer sur le 1er étage du batiement informatique ^|Une fenetre d'information s'ouvre ^|Etre précédement sur la page d'acceuil ^|OK
^|All_G_C.3 ^|Deplacer votre souris sur une salle ^| La salle se colore en fonction de l'etat de batterie du capteur présent dans la salle ^| Etre précédement sur la page du batiment informatique partie maintenance  ^|OK
^|All_G_C.4 ^|Cliquer sur le bouton "Retour" ^|La fenêtre du batiment informatique s'ouvre ^|aucune ^|OK

5+|

|====



|====

>|Cas de test 4+|Test-01-01-03
>|Titre 4+|Visualisation des statistiques d'une salle 
>|Objectif 4+| Obtenir les informations d'une salle via des capteurs représentatif

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur "Statistiques" ^|La fenêtre de statistique des salles s'ouvre ^| Etre connecté à l'interface web (localhost:8000) ^|OK
^|All_G_C.2 ^|Cliquer sur le menu déroulant et selectionner une salle spécifique ^| Les graphique apparaissent avec les dernieres valeurs collectés ^|Etre précédement sur la page d'acceuil  ^|OK
^|All_G_C.3 ^|Selectionner dans le champ de type caldendrier une date et une heure ^| Le calendrier apparait pour selectionner un jour et l'heure ^|aucune ^|OK
^|All_G_C.4 ^|Cliquer sur le bouton "Retour" ^|La fenêtre du batiment informatique s'ouvre ^|aucune ^|OK

5+|

|====

|====

>|Cas de test 4+|Test-01-01-04
>|Titre 4+|Générer un rapport PDF des informations d'une salle spécifiques 
>|Objectif 4+| Obtenir un historique des informations d'une salle via un document PDF

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur "Statistiques" ^|La fenêtre de statistique des salles s'ouvre ^| Etre connecté à l'interface web (localhost:8000) ^|OK
^|All_G_C.2 ^|Cliquer sur le menu déroulant et selectionner une salle spécifique ^| Les graphique apparaissent avec les dernieres valeurs collectés ^| Etre précédement sur la page d'acceuil  ^|OK
^|All_G_C.3 ^|Selectionner dans le champ de type caldendrier une date et une heure ^| Le calendrier apparait pour selectionner un jour et l'heure^| Avoir cliqué sur le champ "Choisir Salle" ^|OK
^|All_G_C.4 ^|Cliquer sur le bouton "Générer un rapport PDF" ^|Un rapport PDF est généré avec les informations de la salle selectionné ^|Acoir renseigné les informations (date et heure)  ^|OK
^|All_G_C.5 ^|Cliquer sur le bouton "Retour" ^|La fenêtre du batiment informatique s'ouvre ^|aucune ^|OK


5+|

|====

== Notes

- Assurez-vous que la base de données est accessible et correctement configurée.
- Confirmez que le Broker MQTT est en cours d'exécution et accessible.
- Examinez les messages de sortie pour détecter les indications de réussite ou d'échec pendant l'exécution du test.
