= Documentation Utilisateur - Sujet "Occupation des salles" (Occupation)
:toc:
:toc-title: Sommaire
//:toc: preamble
:toclevels: 5
:sectnums:
:sectnumlevels: 5

:Entreprise: Groupe 1
:Equipe:  

[cols="4"]
|===
|Version | Date | Équipe | Projet
|1.0 | 12 Janvier 2024 | Groupe 1 : Kylian, Mathéo, Yann, Lylian | Développement d'une application
|=== 

== Présentation de l'Application

=== Objectif de l'application

L'objectif de cette application est de développer une interface de visualisation des données des salles du Batiment B de l'IUT de Blagnac.

=== Rôle de l'application

Cette application permetttra de voir l'occupation des données des salles du Batiment B en temps réel.


== Installation

=== Configuration requise

Avant d’installer l'application, veuillez vous assurer que votre ordinateur satisfait au minimum à la configuration système suivante :

Configuration *matérielle* :

* Processeur : Intel Core i5 ou équivalent
* Mémoire RAM : 8 Go ou plus
* Espace de stockage : 500 Go ou plus
* Écran : Résolution minimale de 1280x800 pixels
* Connexion réseau : Ethernet ou Wi-Fi

Configuration *logicielle* :

* Système d'exploitation : Windows 10, macOS, ou une distribution Linux récente
* Java Development Kit (JDK) : Version 17
* Environnement de développement intégré (IDE) : Eclipse, Visual Studio Code,  IntelliJ IDEA ou NetBeans
* Base de données : Oracle Database, MySQL, ou tout autre système de gestion de base de données relationnelle compatible avec Java
* Bibliothèques/frameworks : JavaFX (pour l'interface utilisateur), JDBC (pour la connexion à la base de données)

== Utilisation



== Fonctionnement



== Résultats produits avec jeux d'essai commentés



== Conclusion

En conclusion, l'application 
